name: terraform fmt
description: terraform fmt
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  working_directory:
    description: working directory
    required: false
    default: ""
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/github-action-format@main
      with:
        github_token: ${{ inputs.github_token }}
        working_directory: ${{ inputs.working_directory }}
        command: terraform fmt -recursive | sed "s|^|${{ inputs.working_directory }}/|"
        commit_message: "style: terraform fmt -recursive"
