name: terraform fmt
description: terraform fmt
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  working_directory:
    description: working directory
    required: false
    default: ""
  skip_push:
    required: false
    description: If "true", this action skips pushing a commit
    default: "false"
  branch:
    required: false
    description: branch where a commit is pushed
    default: ""
  terraform_command:
    required: false
    description: You can execute a tool such as OpenTofu instead of Terraform
    default: terraform
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/github-action-format@073cd378986183fb7d90172aecf130c220979bae # v0.2.2-1
      with:
        github_token: ${{ inputs.github_token }}
        working_directory: ${{ inputs.working_directory }}
        command: |
          "${{inputs.terraform_command}}" fmt -recursive | sed "s|^|${{ inputs.working_directory }}/|"
        commit_message: "style: ${{inputs.terraform_command}} fmt -recursive"
        skip_push: ${{ inputs.skip_push }}
        branch: ${{ inputs.branch }}
